dag_id: "dag_from_emr_jinja_template"
emr:
  instance_type: "m5.xlarge"
  cluster_size: 1
pipeline:
  schedule: "@daily"
  spark:
    jar_loc: "s3://as24-data/artifacts/team/product/spark_app.jar"
    class: "com.as24.data.product.SparkApp"
    input: "s3://as24-data/data/raw/team/product/"
    output: "s3://as24-data/data/processed/team/product/"
  publish:
    bubcket: "s3://as24-data/data/processed/team/product/"
    schema: "product"
    table: "table"
    partition: "date"
    partition_type: "date"